### ISSUE TITLE
Prepare the morphology pre-annotation tool

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#13]
## Summary
In order to ease manually tagging our texts for the gold corpus, a pre-annotation tool which takes into account existing annotated texts must be designed. This tool will fill in unambiguous fields for each word and propose alternatives in columns following the CDLI-CoNLL columns for the user to copy and paste the best choice.

## Tasks
- [x]  Create the outline of the tool, make it accept CDLI-CoNLL input
- [x]  Teach the tool using the extracted list of sequences from ETCSRI (EPP is cleaning up the file at this time)
- [x]  Output pre-annotated morphological annotations
- [x]  Output alternate morpheme sequences in additional columns
- [x]  Data should be stored in an accessible format for consultation

- ~~Should this be offered as a service?~~ 
- What if we feed it badly analyzed texts, will we have to make it relearn all again?  
- Let's always quickly submit the annotated texts after a day of work so other annotators can update their annotated texts bundle for their pre-annotation tool instance to be as efficient as possible.  

#### 📈 Progress (0-1): 1

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by chiarcos** [comment]
On "Should this be offered as a service?": focus on a command-line implementation for the moment, we can offer a wrapper later on.

**Comment by jayanthkmr** [comment]
Converter ATF to CDLI-CoNLL ✅

Pre-annotation tool: https://github.com/cdli-gh/mtaac_work/issues/13 

    Base data (unfinished) https://drive.google.com/drive/folders/0B99LKgTsRaC6R0NXd2dkaWZYLXc?usp=sharing 

    Text examples https://drive.google.com/drive/folders/0B99LKgTsRaC6R0NXd2dkaWZYLXc 

Morphological annotations checker

    Only valid tags

    Columns intact

    …

    Including deleting extra columns

~~Converter to CDLI-CoNLL to ConLL-U~~ #20 

Update the pre-annotation tool issue

**Comment by jayanthkmr** [comment]
https://github.com/cdli-gh/morphology-pre-annotation-tool
