### ISSUE TITLE
Create wireframes

### ISSUE THREAD

**Issue by amanbis** [cdli-gh/mtaac_work#17]
## Summary

Based on the collected data, create wireframes of key user flows so that they can be tested

## Tasks
- [x] Wireframe for search feature (In Progress)
- [ ] Wireframe for browsing collections (In Progress)
- [ ] Wireframe for CDLI journal
- [x] Wireframe for overall website

#### 📈 Progress (0-1): 0.5

See Gantt: http://cdli-dev.org/gantt/mtaac_work/
