### ISSUE TITLE
Converter CDLI-CoNLL to CoNLL-U

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#20]
## Summary
In order to continue the annotation of the texts, we need to convert our home CoNLL format into a full fledged CoNLL-U format. The data can then be exploited by a multitude of other tools. We also have a Converter from CoNLL-U to Brat so the texts can be shipped to the next annotation station: Brat, for syntax and semantics.

The tool must take CDLI-CoNLL as input and output a full CoNLL-U version of the data.

From

```
# ID | FORM | SEGM | XPOSTAG	HEAD	DEPREL	MISC
-- | -- | -- | --
o.1.1 | gurusz# | gurusz | N
o.1.2 | 6(disz)-am3 | 6(disz)-am | NU.COP-3-SG
```
to

```
#ID	FORM	LEMMA	UPOSTAG	XPOSTAG	FEATS	HEAD	DEPREL	DEPS	MISC
-- | -- | -- | --
o.1.1 | gurusz# | gurusz | NOUN | N | ***
o.1.2 | 6(disz)-am3 | 6(disz) | NUM | NU |  **
```

*** Have to check how to systematically mark the morphology using the feats annotation

This tool could be integrated with the morphology pre-annotator.

## Tasks
- [x] Outline the tool... 
- [ ] 
- [x] Document the usage of the tool
- [x] Document how the tool works

#### 📈 Progress (0-1): 1.0

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by chiarcos** [comment]
Should be implemented using CoNLL-RDF, see https://github.com/acoli-repo/conll-rdf:

- CoNLLStreamExtractor to read CDLI-CoNLL
- annotation linking transformation using SPARQL, see https://github.com/cdli-gh/mtaac_work/tree/master/lod/linker
- serialization to CoNLL-U with CoNLLRDFFormatter

Note that https://github.com/cdli-gh/mtaac_work/tree/master/lod/linker contains a pre-release version of CoNLL-RDF

**Comment by epageperron** [comment]
@edihb Please see @chiarcos comment

**Comment by jayanthkmr** [comment]
@epageperron  Please close this issue.
