### ISSUE TITLE
Corpus analysis tool

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#21]
## Summary
We need to choose, test and implement a corpus analysis tool that can manage multiple layers of annotations.

## Tasks and relevant information
- [ ] Choose a tool that seems to have all required features
    - [ ] https://lindat.mff.cuni.cz/services/pmltq/#!/home
    - [ ] http://corpus-tools.org/annis/
    - [ ] Corpus workbench / Ziggurat
    - [ ] XML DB with own SVG frontend
    - [ ] SPARQL endpoint with visualization
    - [ ] Investigate other possibilities
- [ ] Test on CDLI
- [ ] Double check that the tool can scale

The design of the DB schema in Framework might depend on this task.

#### 📈 Progress (0-1): 0.0

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by epageperron** [comment]
Maithili did a survey of the available tools: https://docs.google.com/document/d/1GMrqGdqsqesJSfRvTZYKgn6RVU04lZGbuVMFZ2DVQrU/edit

Current options are (Christian) : 
(1) connect via REST with the ANNIS backend and embedd visualizations
(2) using an existing, standalone corpus information system (e.g., ANNIS, CWB, etc.) in our case **ANNIS**
(3) create something ourselves on top of our RDF rendering of CDLI-CoNLL, visualize via Dot/GraphViz + (4) relational querying of labels

After preparing a mini-workplan for option 3+4 (at next UofT-Frankfurt telco) we can evaluate if we have enough time to build this extension. If not it will be ANNIS with cross-links.
