### ISSUE TITLE
Write documentation for overall design methodology

### ISSUE THREAD

**Issue by amanbis** [cdli-gh/mtaac_work#27]
## Summary

Write documentation for design methodology for CDLI/MTAAC redesign

## Tasks

- [ ] Context
- [ ] Background Research & Moodboards
- [ ] Requirements Informational Interviews
- [ ] UX Informational Interviews
- [ ] Card Sort & Analysis
- [ ] Wireframes
- [ ] Prototyping

#### 📈 Progress (0-1): 1

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by epageperron** [comment]
Hi @amanbis ! When you have a minute, could you please look over your issues and close those that are done and add a explanation comment plus the tag "need help" those that are unfinished?  Thanks!
