### ISSUE TITLE
Morphology scheme

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#9]
## Summary
These tasks will get humans ready to mass annotate our sample texts with morphology. (Building the pre-annotation tool is a separate task)

## Tasks
- [x]  Research morphological tagsets available
- [x] Evaluate tagsets and choose best candidate 
- [x]  Map ETCSRI morph tags to UD
- [x]  Map ETCSRI morph tags to Unimorph
- [x]  Formalize mapping and comments about the mapping in RDF/Turtle
- [x] Convert and tag 10 Ur III texts and note problems
- [x] Extract all unique morphological sequences from ETCSRI in CDLI-CoNLL style
- [x] Write morphological annotation guide

#### 📈 Progress (0-1): 0.9

See gantt: http://cdli-dev.org/gantt/mtaac_work/
